WasmEdge runtime
suborbital/reactr pull request #188
Opened 2021-11-25 03:11 UTC by wangshishuo

Add the runtime using WasmEdge VM.
Build with -tags wasmedge
Reduce loop times in WasmEdge mode for testing with rt.Group

2021-11-25 14:16 UTC, cohix requested changes

2021-11-26 07:52 UTC, wangshishuo commented on docs/wasm.md
> +Install [WasmEdge](https://github.com/WasmEdge/WasmEdge/blob/master/docs/install.md) for using WasmEdge runtime.
Fixed

2021-11-26 07:52 UTC, wangshishuo commented on docs/wasm.md
> +For now, WasmEdge runtime has not been merged into main repo, so we should replace it with your local repo in the `go.mod`, something like:
Fixed

2021-11-26 07:53 UTC, wangshishuo commented on docs/wasm.md
> +go get github.com/second-state/WasmEdge-go@v0.9.0-rc3
Fixed

2021-11-26 07:53 UTC, wangshishuo commented on go.mod
> +	github.com/second-state/WasmEdge-go v0.9.0-rc3.0.20211118175305-d40b88ba25d5
I have updated it to v0.9.0-rc4

2021-11-26 08:36 UTC, wangshishuo commented on docs/wasm.md
> +wget -qO- https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.9.0-rc.2
You are right, I have submitted an [issue](https://github.com/WasmEdge/WasmEdge/issues/845) to record this. But for now, we have to do it manually.
We have uploaded the libraries for M1 to the releases, please try again.

2021-11-26 08:47 UTC, wangshishuo commented on rwasm/runtime/wasmedge/builder.go
> +	err := w.setupAST()
AST stands for Abstract Syntax Tree and is tree representations of code. You can find its meaning [here](https://github.com/WasmEdge/WasmEdge/blob/master/docs/c_api.md#ast-module) n the scenario of WasmEdge C API.

2021-11-26 09:01 UTC, wangshishuo commented on rwasm/runtime/wasmedge/builder.go
> +	wasiImports := wasmedge.NewWasiImportObject(nil, nil, nil, nil)
They are the parameters to be passed to the WASI import object. You can view the details [here](https://github.com/WasmEdge/WasmEdge/blob/0.9.0-rc.4/include/api/wasmedge/wasmedge.h#L2338).

2021-11-26 09:04 UTC, wangshishuo commented
I have update the version of the WasmEdge-go to v0.9.0-rc4 and restored all the `rt.Group` loop count to what it is initial to be. All the test cases passed.

2021-12-02 15:06 UTC, cohix approved these changes

2021-12-02 15:06 UTC, cohix commented on docs/wasm.md
> +brew install llvm
In my experience, this step isn't needed

2021-12-08 14:19 UTC, merged